#ifndef KP_CONSTANTS_H
#define KP_CONSTANTS_H

#define REQUEST_PIPE_NAME "req_pipe"
#define PIPE_PATH "/tmp/"
#define STATUS_OK "OK"
#define STATUS_ERROR "ERROR"

#define UPDATE_CHAT_MILLISECONDS_SLEEP 300
#define UPDATE_CHAT_SECONDS_SLEEP 0
#define MILLISECONDS_SLEEP 300
#define SECONDS_SLEEP 0

#define NONE_USER_NAME "__NONE"
#define SYSTEM_NAME "SYSTEM"
#define COMMAND_ARGS_SEPARATOR '|'
#define COMMAND_SEPARATOR '\n'
#define MIN_NAME_SIZE 2
#define MAX_NAME_SIZE 20
#define MAX_MESSAGE_CHARACTERS 2048

#define CMD_HELP "help"
#define CMD_LOGIN "login"
#define CMD_LOGOUT "logout"
#define CMD_PRIVATE "private"
#define CMD_JOIN "join"
#define CMD_CREATE "create"
#define CMD_PUSH_MSG "push_msg"
#define CMD_GET_MSG "get_msg"
#define CMD_CHATS "chats"

#define CMD_ARG_GROUP "GROUP"
#define CMD_ARG_PRIVATE "PRIVATE"

#define PRINT_SYSTEM_INFO_OK 0
#define PRINT_SYSTEM_INFO_ERR 1
#define PRINT_CHAT_INFO 2
#define PRINT_MESSAGE 3

#define TUI_HORIZONTAL_RATIO 4
#define TUI_VERTICAL_RATIO 5
#define TUI_CHAT_CHOICE_CHAR '>'
#define TUI_CHAT_NOCHOICE_CHAR ' '
#define TUI_CHAT_SEPARATOR_1 " "
#define TUI_CHAT_SEPARATOR_2 ": "
#define TUI_CHAT_SEPARATOR_3 "\n"
#define TUI_MAIN_COLOR_BACK COLOR_BLACK
#define TUI_COLOR_WHITE 1
#define TUI_COLOR_BLUE 2
#define TUI_COLOR_MAGENTA 3
#define TUI_COLOR_RED 4
#define TUI_COLOR_GREEN 5
#define TUI_KEY_EXIT KEY_F(12)
#define TUI_KEY_BACK_TO_MENU KEY_F(2)
#define TUI_KEY_HELP KEY_F(1)

#define TUI_DELAY_MS 100


#endif //KP_CONSTANTS_H
